name: Check secret

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Secret
        uses: actions/checkout@v2

      - name: Validate Secret
        run: |
          if [[ "${{ secrets.MY_SECRET }}" == "123value" ]]; then
            echo "Secret is valid"
          else
            echo "Secret is invalid"
            exit 1
          fi
      - name: Show Secret Value
        run: |
          echo "The secret is ${{ secrets.MY_SECRET }}"
